name: Add Label to PR

on:
  pull_request:
    types: opened

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Add label to PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = ["pr-change"];
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: labels
            });